server:
  port: 9001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_monolith
    username: root
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
